/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tpx3jui_SpidrDaqJ */

#ifndef _Included_tpx3jui_SpidrDaqJ
#define _Included_tpx3jui_SpidrDaqJ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tpx3jui_SpidrDaqJ
 * Method:    ChipConnect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tpx3jui_SpidrDaqJ_ChipConnect
  (JNIEnv *, jobject);

/*
 * Class:     tpx3jui_SpidrDaqJ
 * Method:    ChipDisconnect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tpx3jui_SpidrDaqJ_ChipDisconnect
  (JNIEnv *, jobject);

/*
 * Class:     tpx3jui_SpidrDaqJ
 * Method:    AcqOnOff
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tpx3jui_SpidrDaqJ_AcqOnOff
  (JNIEnv *, jobject);

/*
 * Class:     tpx3jui_SpidrDaqJ
 * Method:    getDeviceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tpx3jui_SpidrDaqJ_getDeviceCount
  (JNIEnv *, jobject);

/*
 * Class:     tpx3jui_SpidrDaqJ
 * Method:    getDacCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tpx3jui_SpidrDaqJ_getDacCount
  (JNIEnv *, jobject);

/*
 * Class:     tpx3jui_SpidrDaqJ
 * Method:    resetDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_tpx3jui_SpidrDaqJ_resetDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     tpx3jui_SpidrDaqJ
 * Method:    resetDevices
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tpx3jui_SpidrDaqJ_resetDevices
  (JNIEnv *, jobject);

/*
 * Class:     tpx3jui_SpidrDaqJ
 * Method:    getDeviceId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_tpx3jui_SpidrDaqJ_getDeviceId
  (JNIEnv *, jobject, jint);

/*
 * Class:     tpx3jui_SpidrDaqJ
 * Method:    getDac
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_tpx3jui_SpidrDaqJ_getDac
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tpx3jui_SpidrDaqJ
 * Method:    setDac
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_tpx3jui_SpidrDaqJ_setDac
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     tpx3jui_SpidrDaqJ
 * Method:    sequentialReadout
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_tpx3jui_SpidrDaqJ_sequentialReadout
  (JNIEnv *, jobject, jint);

/*
 * Class:     tpx3jui_SpidrDaqJ
 * Method:    datadrivenReadout
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tpx3jui_SpidrDaqJ_datadrivenReadout
  (JNIEnv *, jobject);

/*
 * Class:     tpx3jui_SpidrDaqJ
 * Method:    pauseReadout
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tpx3jui_SpidrDaqJ_pauseReadout
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
